# Generated by Django 4.1.1 on 2022-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description1',
            field=models.TextField(default=1, max_length=2000, verbose_name='Qısa məzmun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='description2',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description3',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description4',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description5',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Məzmun4'),
        ),
    ]
