# Generated by Django 4.1.1 on 2022-11-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news', verbose_name='Əsas Şəkil'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Şəkil1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Şəkil2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Şəkil3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Şəkil4'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Şəkil5'),
        ),
    ]
