# Generated by Django 4.1.1 on 2022-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messege',
            field=models.TextField(max_length=2000, verbose_name='Mesaj'),
        ),
    ]
