# Generated by Django 4.1.1 on 2022-09-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon nömrəsi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ad Soyad'),
        ),
    ]
